name: Deploy Image to GCR

on:
  workflow_call:

jobs:
  deploy-cloudrun:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: read
      security-events: write
      id-token: write


    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: authenticate
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/70756149774/locations/global/workloadIdentityPools/github-actions/providers/github-repos'
          service_account: 'hshn-devsecops-service-account@hs-heilbronn-devsecops.iam.gserviceaccount.com'

      - name: Configure Docker
        run: |
          gcloud auth configure-docker europe-west3-docker.pkg.dev

      - name: Login to Github
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Fetch tag push
        run: |
          MY_IMAGE=ghcr.io/${{ github.repository }}/app:${{ github.sha }}
          docker pull $MY_IMAGE
          NEW_IMAGE=europe-west3-docker.pkg.dev/hs-heilbronn-devsecops/note-api/main:${{ github.sha }}
          docker tag $MY_IMAGE $NEW_IMAGE
          docker push $NEW_IMAGE

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: note-api-bigpipe
          image: europe-west3-docker.pkg.dev/hs-heilbronn-devsecops/note-api/main:${{ github.sha }}
          region: europe-west3
          env_vars: BACKEND=memory
          project_id: hs-heilbronn-devsecops
