name: Deploy Image to GCR

on:
  workflow_call:

permissions:
    id-token: write
    contents: read
    packages: write

jobs:
  deploy-cloudrun:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      packages: read

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: authenticate
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/70756149774/locations/global/workloadIdentityPools/github-actions/providers/github-repos'
          service_account: 'hshn-devsecops-service-account@hs-heilbronn-devsecops.iam.gserviceaccount.com'

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: note-api-bigpipe
          image: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/app:${{ github.sha }}
          region: europe-west3
          env_vars: BACKEND=memory