name: Deploy Image to GCR

on:
  workflow_call:

jobs:
  deploy-cloudrun:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: authenticate
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/70756149774/locations/global/workloadIdentityPools/github-actions/providers/github-repos'
          service_account: 'hshn-devsecops-service-account@hs-heilbronn-devsecops.iam.gserviceaccount.com'

      - name: Configure Docker
        run: |
          gcloud auth configure-docker europe-west3-docker.pkg.dev

      - name: Build docker image
        run: |
          docker build -t europe-west3-docker.pkg.dev/hs-heilbronn-devsecops/note-api/bigpipe:${{ github.sha }} .

      - name: Push docker image
        run: |
          docker push europe-west3-docker.pkg.dev/hs-heilbronn-devsecops/note-api/bigpipe:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: note-api-bigpipe
          image: europe-west3-docker.pkg.dev/hs-heilbronn-devsecops/note-api/bigpipe:${{ github.sha }}
          region: europe-west3
          env_vars: BACKEND=memory
          project_id: hs-heilbronn-devsecops