name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main



jobs:

  deploy-cloudrun:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      packages: read
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/70756149774/locations/global/workloadIdentityPools/github-actions/providers/github-repos'
          service_account: 'hshn-devsecops-service-account@hs-heilbronn-devsecops.iam.gserviceaccount.com'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: 'note-api'

      # Step 3: Set up Docker authentication for Google Artifact Registry
      - name: Authenticate Docker with Google Artifact Registry
        run: |
          gcloud auth configure-docker europe-west3-docker.pkg.dev

      # Step 4: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t europe-west3-docker.pkg.dev/${{ secrets.GCP_PID }}/note-api/note-api:${{ github.sha }} .

      # Step 5: Push Docker image to Google Artifact Registry
      - name: Push Docker image to Google Artifact Registry
        run: |
          docker push europe-west3-docker.pkg.dev/${{ secrets.GCP_PID }}/note-api/note-api:${{ github.sha }}

      # Step 6: Deploy to Google Cloud Run
      - name: Deploy to Google Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: 'note-api-hs-heilbronn-devsecops-bigpipe'
          image: 'europe-west3-docker.pkg.dev/${{ secrets.GCP_PID }}/note-api/note-api:${{ github.sha }}'
          region: 'europe-west3'
          env_vars: BACKEND=memory
          project_id: ${{ secrets.GCP_PID }}

  job1:
    uses: ./.github/workflows/python-tests.yml
    secrets: inherit

  job2:
    needs: job1
    uses: ./.github/workflows/security-tests.yml
    secrets: inherit

  job3:
    needs: job2
    uses: ./.github/workflows/docker-image.yml
    secrets: inherit

