name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/python-tests.yml@main

  security-tests:
    needs: test
    uses: ./.github/workflows/security-tests.yml@main

  build-and-push-docker:
    needs: security-tests
    uses: ./.github/workflows/docker-image.yml@main