name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    uses: hs-heilbronn-devsecops-bigpipe/note-api/.github/workflows/python-tests.yml@implement-feedback

  security-tests:
    needs: test
    uses: hs-heilbronn-devsecops-bigpipe/note-api/.github/workflows/security-tests.yml@implement-feedback

  build-and-push-docker:
    needs: security-tests
    uses: hs-heilbronn-devsecops-bigpipe/note-api/.github/workflows/docker-image.yml@implement-feedback