name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push, pull_request, workflow_dispatch]

env:
  BACKEND: memory

jobs:
  Explore-GitHub-Actions:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v4

      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install PIP packages pytest
        run: |
          python -m ensurepip --upgrade
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Run Pytests
        run: |
          pytest -n auto --cov=./ --maxfail=1 -rA -v

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Run Snyk
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - run: echo "Build and push Docker container"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: 'docker-build'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: bigpipe/bigpipe_note-api:latest

      - name: GoogleCloudRunAuthenticate
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'hs-heilbronn-devsecops'
          workload_identity_provider: 'projects/70756149774/locations/global/workloadIdentityPools/github-actions/providers/github-repos'
          service_account: 'hshn-devsecops-service-account@hs-heilbronn-devsecops.iam.gserviceaccount.com'

      - name: Deploy Image to Google Cloud Run
        id: 'deploy-cloudrun'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'note-api-hs-heilbronn-devsecops-bigpipe'
          image: docker.io/bigpipe/bigpipe_note-api:latest
          region: 'europe-west3'

      - name: 'Use output of CloudRun'
        run: 'curl "${{ steps.deploy-cloudrun.outputs.url }}"'

      - run: echo "🍏 This job's status is ${{ job.status }}."