name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test:
    uses: ./.github/workflows/python-tests.yml
    secrets: inherit

  security-tests:
    needs: test
    uses: ./.github/workflows/security-tests.yml
    secrets: inherit

  build-and-push-docker:
    needs: security-tests
    uses: ./.github/workflows/docker-image.yml
    secrets: inherit